### ISSUE TITLE
empty author field + double ask for author name

### ISSUE THREAD

**Issue by tunnckoCore** [generate/generate-package#1]
Using `generate-project` and `generate-generator`, both have the problem, so i think comes from here. Problem also applies for header comment banner of templates like `index.js` and have `ask for author.prop`

``` sh
% ❯ gen dest generator                                                                                     July 09, 16:18:26
[16:18:32] starting generate
[16:18:35] ✔ running tasks: [ 'dest', 'generator' ]
[16:18:35] starting generate.dest 
? Destination directory? chibo
[16:19:38] finished generate.dest 1m
[16:19:39] starting generate.generator 
? Project name? chibo
? Project description? foo bar baz
? Project version? 0.1.0
? Author's GitHub username? tunnckoCore
? Author's name? Charlike Mike Reagent
? Author's URL? tunnckocore.tk
? Author's name?  Charlike Mike Reagent
[16:20:43] finished generate.generator 1m
~  
% ❯
```

It would be better to try to gather author data from git and compose the author string (as in verb).

``` json
{
  "name": "chibo",
  "description": "foo bar baz",
  "version": "0.1.0",
  "homepage": "https://github.com/tunnckoCore/chibo",
  "author": " ()",
  "repository": "tunnckoCore/chibo",
  "bugs": {
    "url": "https://github.com/tunnckoCore/chibo/issues"
  },
  "license": "MIT",
  "files": [
    "index.js"
  ],
  "main": "index.js",
  "engines": {
    "node": ">=0.10.0"
  },
  "scripts": {
    "test": "mocha"
  },
  "keywords": [
    "chibo"
  ]
}
```

**Comment by jonschlinkert** [comment]
I think I fixed that a couple of hours ago. It was because one ask helper had `<%= ask("name") %>` and another had `<%= ask("project.name") %>` and both had the same "question message". It should just be `project.name`. (It's arbitrary, but `project.name` IMO is more clear and less likely to be wrong when generators are combined)

**Comment by jonschlinkert** [comment]
I'll push it up in a few

**Comment by jamen** [comment]
Any updates @jonschlinkert? I am still getting this error with `generate-project`.

In `package.json`:

```
"author": " ()",
```

Also in `LICENSE`:

```
Copyright (c) 2016, .
```

And in `README` (I think):

```
## License

Released under the MIT license. © []()
```

I might be able to make a PR, unless you already got something.

**Comment by jonschlinkert** [comment]
Hmm, I thought I fixed this. If you have a chance, can you try re-installing generate and this package globally?

``` sh
npm cache clean && npm i -g generate generate-package
```

and let me know if you're still having the issue?

**Comment by jamen** [comment]
Seems to have been the cache, that fixed it.  Thanks.  :)

**Comment by jonschlinkert** [comment]
awesome! thanks for the update!

**Comment by jonschlinkert** [comment]
@tunnckoCore can you confirm if this is fixed for you?

**Comment by tunnckoCore** [comment]
yep :+1:
